server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mscatalog 
          uri: lb://catalog-service 
          predicates: 
            - Path=/catalog/**        

        - id: msserie 
          uri: lb://serie-service 
          predicates: 
            - Path=/serie/**  


info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints: 
      web:
        exposure:
          include: gateway
